name: dart_nats_streaming
description: A client for NATS Streaming Server.
version: 0.0.5
homepage: https://github.com/consultoriadigital-pt/dart-nats-streaming

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^3.0.2
  dart_nats: ^0.2.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  pedantic: ^1.9.0
  retry: ^3.1.0

dev_dependencies:
  test: ^1.14.4
